BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `Unterkunft` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT NOT NULL UNIQUE,
	`email`	TEXT,
	`telnr`	TEXT,
	`authtoken`	TEXT UNIQUE
);
CREATE TABLE IF NOT EXISTS  `Objekt` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT NOT NULL UNIQUE,
	`image`	TEXT
);
CREATE TABLE IF NOT EXISTS  `Bedarf` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`unterkunft_id`	INTEGER NOT NULL,
	`objekt_id`	INTEGER NOT NULL,
	FOREIGN KEY(`unterkunft_id`) REFERENCES Unterkunft(id),
	FOREIGN KEY(`objekt_id`) REFERENCES Objekt(id)
);
COMMIT;
