<?php
require(__DIR__ . '/fpdf/fpdf.php');
require(__DIR__ . '/phpqrcode/qrlib.php');
require(__DIR__ . '/db.php');

$id = $_GET['id'];

//check if the id is benevolent
if (!preg_match("/^[a-z]*-[a-z]*-[a-z]*$/", $id)) {
    die("id doesn't look like it has been generated by us, sorry :(");
}

$db = new MyDB();

$accommodation = $db->getAccommodationFromToken($id);
if (!$accommodation) {
    die("id doesn't seem to link to a valid accomodation or it has been given out twice");
}

$unterkunft = $accommodation['name'];
$unterkunft_html = $accommodation['clean_name'];

$server_url = 'http://donutplanet.de:1337';
$readonly_list = $server_url . '/unterkunft/' . $unterkunft_html;
$codeText = $server_url . '/a/'.$id;
$qrfile = '/tmp/' . $id . '.png';

QRcode::png($codeText, $qrfile, null, 20);

$pdf = new FPDF();
$pdf->AddPage();
$pdf->SetFont('Arial', 'B', 16);
$pdf->Cell(null,null,"Editierbare Bedarfsliste für " . $unterkunft,null,null,"C");
$pdf->Ln();
$pdf->Image($qrfile,$pdf->w/2-20,$pdf->GetY()+10,40,null,'PNG');
$pdf->Ln();
$pdf->Cell(null,$pdf->GetY()+100,$codeText,null,null,"C");
$pdf->Ln();
$pdf->Ln();
$pdf->Cell(null,60, "Unter diesem Link (oder QR code) findest du die Bedarfsliste für deine Unterkunft. Ihr könnt euch den Link als Lesezeichen speichern aber bitte stellt sicher, dass nur Leute, die die Liste bearbeiten dürfen zugang zum Link haben");
$pdf->Ln();
$pdf->Ln();
$pdf->Cell(null,60, "Eine nur-lesen version der Liste zum Facebook teilen und ausgeben an mögliche Spender findet ihr unter" . $readonly_list . ".");
unlink($qrfile);
$pdf->Output();
?>
