<?php
require(__DIR__ . '/fpdf/fpdf.php');
require(__DIR__ . '/phpqrcode/qrlib.php');

$id = $_GET['id'];

//check if the id is benevolent
if (!preg_match("/^[a-z]*-[a-z]*-[a-z]*$/", $id)) {
    die("id doesn't look like it has been generated by us, sorry :(");
}

$codeText = 'http://donutplanet.de:1337/a/'.$id; 
$qrfile = '/tmp/' . $id . '.png';
error_log("[INFO] qrfile is " . $qrfile);

QRcode::png($codeText, $qrfile);

$pdf = new FPDF();
$pdf->AddPage();
$pdf->SetFont('Arial','B',16);
$pdf->Cell(40,10,'Hello World!');
$pdf->image($qrfile,40,20,0,0,'PNG');
unlink($qrfile);
$pdf->Output();
?>
