<?php
require(__DIR__ . '/db.php');

$id = $_GET['id'];

//check if the id is benevolent
if (!preg_match("/^[a-z]*-[a-z]*-[a-z]*$/", $id)) {
    die("id doesn't look like it has been generated by us, sorry :(");
}

$db = new MyDB();

$accommodation = $db->getAccommodationFromToken($id);
if (!$accommodation) {
    die("id doesn't seem to link to a valid accomodation or it has been given out twice");
}

$unterkunft = $accommodation['name'];
$unterkunft_html = $accommodation['clean_name'];

$server_url = 'http://donutplanet.de:1337';
$readonly_list = $server_url . '/unterkunft/' . $unterkunft_html;
$codeText = $server_url . '/a/'.$id;
?>
<html>
  <head>
	<title>
	asdf
	</title>
	<link rel="stylesheet" href="/print.css" />
  </head>
  <body>
	<div class="center">
	<h1>Editierbare Bedarfsliste für <?php echo $unterkunft; ?></h1>
	<img src="/qr.php?id=<?php echo $id; ?>" /><br />
	<?php echo $codeText; ?>
	<div class=multicol">
	Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. 
	<br />
	Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. 
	<br />
	Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. 
	<br />
	Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. 
	</div>
	</div>
  </body>
</html>
